//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietYCMH
    {
        public double ID { get; set; }
        public double Line { get; set; }
        public string MaYCMH { get; set; }
        public double MaSanPham { get; set; }
        public string TenSP { get; set; }
        public double SoLuong { get; set; }
        public string DVT { get; set; }
        public string Size { get; set; }
    
        public virtual Sanpham Sanpham { get; set; }
        public virtual YeuCauMuaHang YeuCauMuaHang { get; set; }
    }
}
