//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.YeuCauMuaHangs = new HashSet<YeuCauMuaHang>();
        }
    
        public string MaNCC { get; set; }
        public string Ten { get; set; }
        public string PhapNhan { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string DiaChiMail { get; set; }
        public string TrachNhiem { get; set; }
        public Nullable<double> MST { get; set; }
        public string LoaiHinhThue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauMuaHang> YeuCauMuaHangs { get; set; }
    }
}
