//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanHang
    {
        public double MaNhan { get; set; }
        public double NgayNhan { get; set; }
        public double MaDonHang { get; set; }
    
        public virtual DateTime DateTime { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
